# Generated by Django 5.1.4 on 2025-05-07 11:33

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='social_media_links',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='bg_col',
            field=colorfield.fields.ColorField(default='#fffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='brand',
            field=models.CharField(default='MyBrand', max_length=255),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='footer_bg_col',
            field=colorfield.fields.ColorField(default='bg-wine', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='nav_col',
            field=colorfield.fields.ColorField(default='bg-wine', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='footer',
            name='copyright_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='contact_email',
            field=models.EmailField(default='YourEmail', max_length=254),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='contact_phone',
            field=models.CharField(default='YourPhoneNo', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitelogo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site_logo'),
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='site_settings.footer')),
            ],
        ),
    ]
