# Generated by Django 5.1.4 on 2025-05-14 21:41

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_remove_footer_social_media_links_siteinfo_bg_col_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='bg_col',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='footer_bg_col',
            field=colorfield.fields.ColorField(default='#c9c3c3', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='nav_col',
            field=colorfield.fields.ColorField(default='#c9c3c3', image_field=None, max_length=25, samples=None),
        ),
    ]
